num_epochs: 200
batch_size: 82
device: all
run_name: run_1
work_dir: results/mamba_val_no_recuse
seed: 42
k: 56
# batch_pbar: true
optim:
  name: adamw
  lr: 5e-4
  kwargs:
    weight_decay: 5e-5
loss:
  name: mse_loss
  # name: mse_fourier_loss
  # kwargs:
  #   recon_weight: 0.1
  #   fourier_weight: 1.0
  # name: mse_fc_loss
  # kwargs:
  #   mse_weight: 0.5
  #   fc_weight: 0.5
  # name: mse_first_loss
  # kwargs:
  #   recon_weight: 0.25
  #   first_weight: 0.75
# grad_clip:
#   max_norm: 1.0
# scheduler: null
scheduler:
  name: onecycle
  kwargs:
    max_lr: ${optim.lr}
    # total_steps: 2000
    pct_start: 0.0
    epochs: ${num_epochs}
    steps_per_epoch: 4
    div_factor: 250.0
    final_div_factor: 100000.0
model:
  name: mamba
  print_summary: true
  num_models_to_save: 2
  save_last: true
  # freeze_modules:
  #   - blocks
  # unfreeze_modules:
  #   - lora
  #   - norm
  init: null 
  # init: 
  #   weights: results/ddp_test/run_1/models/final_model.pt
  #   weights_only: true
  #   strict: false
  ########## Mamba Model
  kwargs:
    num_blocks: 2
    d_model: ${data.num_regions}
    d_state: 256
    d_conv: 8
    expand: 4
    dropout: 0.3
    steps: 8
  ########## Transformer with lora
  # kwargs:
  #   in_features: ${data.num_regions}
  #   num_heads: 2
  #   steps: 8
  #   num_blocks: 1
  #   # masked_attn: true
  #   attn_drop_prob: 0.25
  #   final_drop_prob: 0.25
  #   ffn_dropout: 0.25
  # pred_len: ${data.pred_len}
  # use_lora: true
  # alpha: 64
  # r: 64
  ######### NPI MLP
  # kwargs:
  #   input_dim: 1200
  #   hidden_dim: 800
  #   latent_dim: 320
  #   output_dim: 400
  #   steps: 3
########## GCN
# kwargs:
#   num_features: 20
#   hidden_dim: 128
# kwargs:
#   num_features: 20
#   hidden_dim: 128
######### GCTN
# kwargs:
#   in_channels: 20
#   out_channels: 1
#   heads: 12
#   dropout: 0.0
# kwargs:
#   in_channels: 20
#   out_channels: 1
#   heads: 12
#   dropout: 0.0
########## STGCN
# kwargs:
#   num_nodes: 360
#   in_features: 1
#   hidden_dim: 10
#   out_features: 1
# kwargs:
#   num_nodes: 360
#   in_features: 1
#   hidden_dim: 10
#   out_features: 1
callbacks:
  use_early_stopping: false
  patience: 5
  threshold: 0.0001
data:
  train_proportion: 0.8
  noise_strength: 1.0
  # pred_len: 8
  target_tr: 2
  num_regions: 400
  train:
    step: ${model.kwargs.steps}
    shuffle: true
    # threshold: 0.8
  val:
    step: ${data.train.step}
    shuffle: false
    # threshold: 0.8
